#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_image_load_formatted : enable
#extension GL_EXT_debug_printf : enable

#include "raycommon.glsl"

struct Factors {
  float ratio;
  float blend;
};

layout(set = 0, binding = 1) uniform image2D inImage0;
layout(set = 0, binding = 4) buffer _buf0 { float noisy[]; };
layout(set = 0, binding = 7) buffer _buf1 { float denoised[]; };
layout(set = 0, binding = 8) buffer _buff2 { Range foveatedRangeBuffer[];};

#define GRID_SIZE 16
layout(local_size_x = GRID_SIZE, local_size_y = GRID_SIZE) in;

Factors calcRatio(ivec2 pixel){
    Factors f;

    ivec2 imageCenter = ivec2(imageSize(inImage0)) / 2;
    float dist = length(pixel - imageCenter);

    float innerRatio = foveatedRangeBuffer[0].ratio;
    float outerRatio = foveatedRangeBuffer[1].ratio;

    float innerRadius = foveatedRangeBuffer[0].outerRadius;
    float outerRadius = foveatedRangeBuffer[1].innerRadius;

    if(dist <= innerRadius){
        f.ratio = 1.;
        f.blend = 1.;
        return f;
    }

    if(dist > outerRadius){
        f.ratio = 0.;
        f.blend = 0.;
        return f;
    }

    float ratio = (dist - innerRadius) / (outerRadius - innerRadius);
    ratio = pow(ratio, 1);
    f.blend = 1 - ratio;
    ratio *= (outerRatio - innerRatio);
    ratio += innerRatio;
    f.ratio = ratio;
    return f;
}

void main()
{
    // debugPrintfEXT("%d\n", gl_GlobalInvocationID.x);
  ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
  Factors f = calcRatio(pixel);
  vec2 seed = vec2(pixel) / (gl_NumWorkGroups * gl_WorkGroupSize).xy;
  float p = rand(seed) / 2 + 0.5;
  if(f.blend == 0. || p > 1. / f.ratio)
      return;

  ivec2 imgSize = imageSize(inImage0);
  ivec2 coord   = ivec2(gl_GlobalInvocationID.xy);
  if(coord.x >= imgSize.x || coord.y >= imgSize.y)  // Check limits
    return;

  uint linear = coord.y * imgSize.x * 3 + coord.x * 3;

  vec3 noisyPixel = vec3(noisy[linear], noisy[linear+1], noisy[linear+2]) / f.ratio;
  vec3 denoisedPixel = vec3(denoised[linear], denoised[linear+1], denoised[linear+2]);
  vec3 result = mix(denoisedPixel, noisyPixel, f.blend);
  denoised[linear] = result.r;
  denoised[linear + 1] = result.g;
  denoised[linear + 2] = result.b;
}