#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_debug_printf : enable

#include "raycommon.glsl"
#include "random.glsl"

layout(location = 0) rayPayloadEXT hitPayload prd;

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 4) buffer _buff { float rgbBuffer[]; };
layout(set = 0, binding = 5) buffer _buf1 { float albedoBuffer[]; };
layout(set = 0, binding = 6) buffer _buf2 { float normalBuffer[]; };
layout(set = 0, binding = 7) buffer _buf3 { float flowBuffer[]; };

layout(set = 2, binding = 0) uniform UBO {
    mat4 currLeftProj;
	mat4 currLeftView;
    mat4 currRightProj;
	mat4 currRightView;
    
	mat4 currLeftProjInv;
	mat4 currLeftViewInv;
	mat4 currRightProjInv;
	mat4 currRightViewInv;

    mat4 prevLeftProj;
    mat4 prevLeftView;
    mat4 prevRightProj;
    mat4 prevRightView;
} ubo;

layout(push_constant) uniform constants {
    float timestamp;
    int frame;
};

uint  rayFlags = gl_RayFlagsNoneEXT;
float tMin     = 0.00001;
float tMax     = 10000.0;

bool isRightCamera = false;
mat4 currProj;
mat4 currView;
mat4 currProjInv;
mat4 currViewInv;

mat4 prevProj;
mat4 prevView;

void fillBuffers(ivec2 pixel){
    uint linearV2 = pixel.y * gl_LaunchSizeEXT.x * 2 + pixel.x * 2;
    vec2 prevPixel = vec2(prevProj * prevView * vec4(prd.hitPoint, 1.));
    vec2 opticalFlow = pixel - prevPixel;
    flowBuffer[linearV2] = opticalFlow.x;
    flowBuffer[linearV2 + 1] = opticalFlow.y;

    uint linearV3 = pixel.y * gl_LaunchSizeEXT.x * 3 + pixel.x * 3;
    vec3 cameraNormal = normalize(mat3(ubo.currLeftView) * prd.normal);
    cameraNormal.g *= -1;
    normalBuffer[linearV3] = cameraNormal.x;
    normalBuffer[linearV3 + 1] = cameraNormal.y;
    normalBuffer[linearV3 + 2] = cameraNormal.z;

    albedoBuffer[linearV3] = prd.albedo.r;
    albedoBuffer[linearV3 + 1] = prd.albedo.g;
    albedoBuffer[linearV3 + 2] = prd.albedo.b;

    rgbBuffer[linearV3] = 0.;
    rgbBuffer[linearV3 + 1] = 0.;
    rgbBuffer[linearV3 + 2] = 0.;
}

void prePass(ivec2 pixel){
    uvec2 coords = pixel;
    if(isRightCamera)
        coords.x -= gl_LaunchSizeEXT.x / 2;
    vec2 inUV = (vec2(coords) + vec2(0.5)) / (vec2(gl_LaunchSizeEXT.xy) / 2);


    vec2 d = inUV * 2.0 - 1.0;
    vec3 origin    = (currViewInv * vec4(0, 0, 0, 1)).xyz;
    vec3 target    = (currProjInv * vec4(d.x, d.y, 1, 1)).xyz;
    vec3 direction = (currViewInv * vec4(normalize(target), 0)).xyz;

    prd.fillGuideLayers = true;
    prd.hitValue = vec3(0.);
    prd.depth = 0;
    prd.albedo = vec3(0.);
    prd.normal = vec3(0.);
    
    traceRayEXT(topLevelAS, // acceleration structure
        rayFlags,       // rayFlags
        0xFF,           // cullMask
        0,              // sbtRecordOffset
        0,              // sbtRecordStride
        0,              // missIndex
        origin,  // ray origin
        tMin,           // ray min range
        direction,  // ray direction
        tMax,           // ray max range
        0               // payload (location = 0)
    );
    prd.fillGuideLayers = false;

    fillBuffers(pixel);
}

vec3 rayTrace(ivec2 pixel, int i){
    vec2 coords = pixel;
    if(isRightCamera)
        coords.x -= gl_LaunchSizeEXT.x / 2;
    vec2 offset = vec2(rnd(prd.seed), rnd(prd.seed)) - vec2(.5);
    vec2 targetCoords = vec2(coords) + offset;
    vec2 inUV = (vec2(coords) + vec2(0.5)) / (vec2(gl_LaunchSizeEXT.xy) / 2);

    vec2 d = inUV * 2.0 - 1.0;
    vec3 origin    = (currViewInv * vec4(0, 0, 0, 1)).xyz;
    vec3 target    = (currProjInv * vec4(d.x, d.y, 1, 1)).xyz;
    vec3 direction = (currViewInv * vec4(normalize(target), 0)).xyz;

    // vec2 targetCoords = vec2(pixel) + offset;
    // vec2 inUV = targetCoords / vec2(gl_LaunchSizeEXT.xy);
    // vec2 d = inUV * 2.0 - 1.0;

    // vec3 origin    = (ubo.currLeftViewInv * vec4(0, 0, 0, 1)).xyz;
    // vec3 target    = (ubo.currLeftProjInv * vec4(d.x, d.y, 1, 1)).xyz;
    // vec3 direction = (ubo.currLeftViewInv * vec4(normalize(target), 0)).xyz;

    prd.hitValue = vec3(0.);
    prd.depth = 0;

    traceRayEXT(topLevelAS, // acceleration structure
        rayFlags,       // rayFlags
        0xFF,           // cullMask
        0,              // sbtRecordOffset
        0,              // sbtRecordStride
        0,              // missIndex
        origin,  // ray origin
        tMin,           // ray min range
        direction,  // ray direction
        tMax,           // ray max range
        0               // payload (location = 0)
    );
    return prd.hitValue;
}

void main() 
{
    ivec2 pixel = ivec2(gl_LaunchIDEXT.xy);
    if(pixel.x > gl_LaunchSizeEXT.x / 2){
        isRightCamera = true;
        currProj = ubo.currRightProj;
        currView = ubo.currRightView;
        currProjInv = ubo.currRightProjInv;
        currViewInv = ubo.currRightViewInv;

        prevProj = ubo.prevRightProj;
        prevView = ubo.prevRightView;
    }
    else{
        currProj = ubo.currLeftProj;
        currView = ubo.currLeftView;
        currProjInv = ubo.currLeftProjInv;
        currViewInv = ubo.currLeftViewInv;

        prevProj = ubo.prevLeftProj;
        prevView = ubo.prevLeftView;
    }

    prePass(pixel);

    prd.depth = 0;
    uint thread_id = gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x;
    uint time_seed = uint(timestamp * 10e10);
    prd.seed = tea(thread_id + time_seed, thread_id - time_seed);
    int sampleCount = 1;
    vec3 finalColor = vec3(0.);
    for(int i = 0; i < sampleCount; i++){
        prd.seed += i;
        finalColor += rayTrace(pixel, i);
    }
    finalColor = finalColor / float(sampleCount);

    // gamma correction
    uint linear = pixel.y * gl_LaunchSizeEXT.x * 3 + pixel.x * 3;
    rgbBuffer[linear] = sqrt(finalColor.r);
    rgbBuffer[linear + 1] = sqrt(finalColor.g);
    rgbBuffer[linear + 2] = sqrt(finalColor.b);
}
